name = "wallytutor-registry"
uuid = "1c8d5cd5-4f2f-4bf2-a100-d894ff3ca1f1"
repo = "https://github.com/wallytutor/wallytutor-registry"

[packages]
0dff88b2-42f1-4682-ada6-3beed8c0a17c = { name = "DryTooling", path = "D/DryTooling" }
573d4978-4615-42ee-907a-4f7d0c4f09b5 = { name = "RadCalNet", path = "R/RadCalNet" }
8d904351-f17f-419c-aa8d-05d4f5cffd52 = { name = "DryToolingCore", path = "D/DryToolingCore" }
