name = "wallytutor-registry"
uuid = "a427d7b3-1a63-4f83-80e3-50e8b391775f"
repo = "https://github.com/wallytutor/wallytutor-registry"

[packages]
0dff88b2-42f1-4682-ada6-3beed8c0a17c = { name = "DryTooling", path = "D/DryTooling" }
573d4978-4615-42ee-907a-4f7d0c4f09b5 = { name = "RadCalNet", path = "R/RadCalNet" }
8b2daee5-fc71-482f-9f0c-337f5aafbbbc = { name = "PkgOther", path = "P/PkgOther" }
e53c8557-27ca-4b42-9400-5de0a806af68 = { name = "PkgCore", path = "P/PkgCore" }
